apiVersion: v2.edp.epam.com/v1alpha1
kind: Template
metadata:
  name: quarkus-java21
spec:
  buildTool: maven
  category: api
  description: >-
    Build fast and lightweight Java applications with Quarkus, a
    Kubernetes-native Java framework designed for GraalVM and OpenJDK HotSpot.
    This template supports Quarkus with Java 21, enabling rapid development of
    RESTful microservices with minimal footprint and blazing fast startup times.
    Ideal for cloud-native environments and containerized deployments.
  displayName: Simple Quarkus Hello World Application
  framework: quarkus
  icon:
    - base64data: >-
        PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPCEtLSBVcGxvYWRlZCB0bzogU1ZHIFJlcG8sIHd3dy5zdmdyZXBvLmNvbSwgR2VuZXJhdG9yOiBTVkcgUmVwbyBNaXhlciBUb29scyAtLT4KPHN2ZyB3aWR0aD0iODAwcHgiIGhlaWdodD0iODAwcHgiIHZpZXdCb3g9Ii0wLjUgMCAyNTcgMjU3IiB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHByZXNlcnZlQXNwZWN0UmF0aW89InhNaWRZTWlkIj4KICAgIDxnPgogICAgICAgIDxwYXRoIGQ9Ik0yMTMuNTU0Mjg2LDAgQzIzNi45NzE4MDksMC4wODA4ODU2OTU2IDI1NS45MzEyNDgsMTkuMDUyMjg1OSAyNTUuOTk3MzYzLDQyLjQ2OTg1NTQgTDI1NS45OTczNjMsNDIuNDY5ODU1NCBMMjU1Ljk5NzM2MywyMTMuNTU0Mjg2IEMyNTUuOTMxMTcyLDIzNi45ODIyNjcgMjM2Ljk1NTQ4OSwyNTUuOTU3OTUgMjEzLjUyNzUwOCwyNTYuMDI0MTQxIEwyMTMuNTI3NTA4LDI1Ni4wMjQxNDEgTDE4OC4wODg0MzksMjU2LjAyNDE0MSBMMTc2LjQyNjYzNSwyMjcuNzA2NDQxIEwyMTMuNTU0Mjg2LDIyNy43MDY0NDEgQzIyMS4zMjgwOTgsMjI3LjYwNTQ3IDIyNy42MDU0NywyMjEuMzI4MDk4IDIyNy43MDY0NDEsMjEzLjU1NDI4NiBMMjI3LjcwNjQ0MSwyMTMuNTU0Mjg2IEwyMjcuNzA2NDQxLDQyLjQ2OTg1NTQgQzIyNy42MDU0NywzNC42OTYwNDM2IDIyMS4zMjgwOTgsMjguNDE4NjcxMyAyMTMuNTU0Mjg2LDI4LjMxNzcgTDIxMy41NTQyODYsMjguMzE3NyBMNDIuNDY5ODU1NCwyOC4zMTc3IEMzNC42OTYwNDM2LDI4LjQxODY3MTMgMjguNDE4NjcxMywzNC42OTYwNDM2IDI4LjMxNzcsNDIuNDY5ODU1NCBMMjguMzE3Nyw0Mi40Njk4NTU0IEwyOC4zMTc3LDIxMy41NTQyODYgQzI4LjQxODY3MTMsMjIxLjMyODA5OCAzNC42OTYwNDM2LDIyNy42MDU0NyA0Mi40Njk4NTU0LDIyNy43MDY0NDEgTDQyLjQ2OTg1NTQsMjI3LjcwNjQ0MSBMMTA1LjA3Njc0MiwyMjcuNzA2NDQxIEwxMjguMDEyMDcxLDE3OS4yMTE1NDMgTDE1OS42MzY4NSwyNTYuMDI0MTQxIEw0Mi40Njk4NTU0LDI1Ni4wMjQxNDEgQzE5LjA0MTg3NDIsMjU1Ljk1Nzk1IDAuMDY2MTkxNTIxOSwyMzYuOTgyMjY3IDAsMjEzLjU1NDI4NiBMMCwyMTMuNTU0Mjg2IEwwLDQyLjQ2OTg1NTQgQzAuMDY2MTkxNTIxOSwxOS4wNDE4NzQyIDE5LjA0MTg3NDIsMC4wNjYxOTE1MjE5IDQyLjQ2OTg1NTQsMCBMNDIuNDY5ODU1NCwwIEwyMTMuNTU0Mjg2LDAgWiBNMTY5LjU3MTQ3NSwxMzkuNzI3NDMxIEwxNjkuNTcxNDc1LDE4NS4yMzY1ODYgTDEzMC4xNTQzMDgsMTYyLjQ4ODcwMyBMMTY5LjU3MTQ3NSwxMzkuNzI3NDMxIFogTTg2LjQ1MjY2Niw5NC4yMTgyNzY1IEw4Ni40NTI2NjYsMTM5LjcyNzQzMSBMNDcuMDM1NDk4OCwxMTYuOTY2MTU5IEw4Ni40NTI2NjYsOTQuMjE4Mjc2NSBaIE0xNjcuNDI5MjM4LDQ0Ljk4Njk4NDUgTDE2Ny40MjkyMzgsOTAuNDk2MTM5MiBMMTI4LjAxMjA3MSw2Ny43MzQ4NjcxIEwxNjcuNDI5MjM4LDQ0Ljk4Njk4NDUgWiIgZmlsbD0iIzQ2OTVFQiI+Cg08L3BhdGg+CiAgICAgICAgPHBhdGggZD0iTTg2LjQ1MjY2NiwxMzkuNzI3NDMxIEwxMjUuODY5ODMzLDE2Mi40ODg3MDMgTDg2LjQ1MjY2NiwxODUuMjM2NTg2IEw4Ni40NTI2NjYsMTM5LjcyNzQzMSBaIE0xNjkuNTcxNDc1LDk0LjIxODI3NjUgTDIwOC45ODg2NDIsMTE2Ljk2NjE1OSBMMTY5LjU3MTQ3NSwxMzkuNzI3NDMxIEwxNjkuNTcxNDc1LDk0LjIxODI3NjUgWiBNODguNTk0OTAzNSw0NC45ODY5ODQ1IEwxMjguMDEyMDcxLDY3LjczNDg2NzEgTDg4LjU5NDkwMzUsOTAuNDk2MTM5MiBMODguNTk0OTAzNSw0NC45ODY5ODQ1IFoiIGZpbGw9IiNGRjAwNEEiPgoNPC9wYXRoPgogICAgICAgIDxwYXRoIGQ9Ik04Ni40NTI2NjYsOTQuMjE4Mjc2NSBMMTI1Ljg2OTgzMywxMTYuOTY2MTU5IEwxMjUuODY5ODMzLDE2Mi40ODg3MDMgTDg2LjQ1MjY2NiwxMzkuNzI3NDMxIEw4Ni40NTI2NjYsOTQuMjE4Mjc2NSBaIE0xNjkuNTcxNDc1LDk0LjIxODI3NjUgTDE2OS41NzE0NzUsMTM5LjcyNzQzMSBMMTMwLjE1NDMwOCwxNjIuNDg4NzAzIEwxMzAuMTU0MzA4LDExNi45NjYxNTkgTDE2OS41NzE0NzUsOTQuMjE4Mjc2NSBaIE0xMjguMDEyMDcxLDY3LjczNDg2NzEgTDE2Ny40MjkyMzgsOTAuNDk2MTM5MiBMMTI4LjAxMjA3MSwxMTMuMjU3NDExIEw4OC41OTQ5MDM1LDkwLjQ5NjEzOTIgTDEyOC4wMTIwNzEsNjcuNzM0ODY3MSBaIiBmaWxsPSIjMDkxMzEzIj4KDTwvcGF0aD4KICAgIDwvZz4KPC9zdmc+
      mediatype: image/svg+xml
  keywords:
    - quarkus
    - java
    - api
    - microservice
  language: java
  maintainers:
    - email: SupportEPMD-EDP@epam.com
      name: SupportEPMD-EDP
  maturity: stable
  minEDPVersion: 3.4.0
  source: https://github.com/KubeRocketCI/template-quarkus
  type: application
  version: 0.1.0
